<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^[^#]*(\([^\)]*$|\{\s*$)</string>
	<key>foldingStopMarker</key>
	<string>(^\s*\)|^\s*\})</string>
	<key>name</key>
	<string>cInt</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.cInt</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.cInt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[\[[^\]]*\]\]</string>
			<key>name</key>
			<string>keyword.tag.cInt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[\[[^]]*\]\])|([0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{2})|([0-9]{2}:[0-9]{2}:[0-9]{2}-[0-9]?{2})</string>
			<key>name</key>
			<string>constant.timecode.cInt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>Interviewer[ 0-9a-zA-Z]?{3}|Respondent[ 0-9a-zA-Z]?{3}|Notes[ 0-9a-zA-Z]?{3}|^Unknown$|\[interviewer[ 0-9a-zA-Z]?{3}\]|\[respondent[ 0-9a-zA-Z]?{3}\]|\[note[ 0-9a-zA-Z]?{3}\]</string>
			<key>name</key>
			<string>keyword.speaker.cInt</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cInt</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cInt</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.bracket.cInt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.cInt</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cInt</string>
	<key>uuid</key>
	<string>B0E0AA33-E28E-45FC-B966-5F5DB1862C27</string>
</dict>
</plist>
